import type { PlotMachineDefinition } from './types';

export const V07_PLOT_MACHINE: PlotMachineDefinition = {
  id: 'v07',
  targetId: 'route:v07',
  title: '第七卷路线开关',
  // 中文注释：路线事实副 API 只在第七章内辅助记录剧情倾向。
  // 2013-03-04 是 SAE_07-8 结束后由玩家强制选线的 DDL，当天起检查器必须关闭；
  // 即使副 API 没运行、失败或所有事实都是 0，也不能限制玩家选择“留下 / 单飞 / 朱音”。
  proposalWindow: {
    start: '2013-02-08',
    end: '2013-03-03',
  },
  promptWindow: {
    start: '2013-03-04',
    end: '2013-03-31',
  },
  choiceStorageKey: 'plotRoute.v07.choice',
  routes: [
    {
      id: 'stay_blackgold',
      familyId: 'stay',
      label: '黑金留下',
      requiredFlagIds: [
        'megumi_coplanner',
        'second_project_seed_ready',
        'blackgold_counterwill',
        'eriri_high_battlefield_supported',
        'utaha_author_pride_supported',
        'user_knows_counterwill',
        'akane_repulsed',
      ],
    },
    {
      id: 'stay_user_only',
      familyId: 'stay',
      label: 'User 独自留下',
      requiredFlagIds: [
        'user_stay_commitment_grounded',
        'blackgold_not_staying_confirmed',
        'user_stay_position_available',
      ],
    },
    {
      id: 'akane_core',
      familyId: 'akane',
      label: '朱音核心线',
      requiredFlagIds: ['akane_pressure_seen', 'akane_formal_offer_seen', 'akane_route_open'],
    },
    {
      id: 'solo_user_exit',
      familyId: 'solo',
      label: 'User 独自单飞',
      requiredFlagIds: ['solo_route_open', 'user_exit_commitment_grounded'],
    },
    {
      id: 'solo_group_exit_except_tomoya',
      familyId: 'solo',
      label: '除伦也外集体单飞',
      requiredFlagIds: [
        'solo_route_open',
        'group_exit_without_tomoya_grounded',
        'group_exit_participant_snapshot_ready',
      ],
    },
  ],
  flags: [
    {
      id: 'akane_pressure_seen',
      storageKey: 'plotFlag.v07.akane_pressure_seen',
      earliestDate: '2013-02-25',
      label: '朱音压力已被看见',
      yesMeaning: 'User 已知道红坂朱音压力存在。',
      noMeaning: '本轮明确表明 User 尚未知道红坂朱音压力。',
    },
    {
      id: 'akane_formal_offer_seen',
      storageKey: 'plotFlag.v07.akane_formal_offer_seen',
      earliestDate: '2013-02-25',
      label: '正式挖角已进入视野',
      yesMeaning: '御影亭或《寰域编年纪》的正式挖角压力已被显性得知。',
      noMeaning: '正式挖角尚未进入路线判断。',
    },
    {
      id: 'blackgold_shaken',
      storageKey: 'plotFlag.v07.blackgold_shaken',
      earliestDate: '2013-02-25',
      label: '黑金被朱音战场动摇',
      yesMeaning: '英梨梨、诗羽被红坂朱音提供的高强度战场动摇。',
      noMeaning: '本轮明确表明黑金二人组尚未被朱音战场动摇。',
    },
    {
      id: 'akane_route_open',
      storageKey: 'plotFlag.v07.akane_route_open',
      earliestDate: '2013-02-25',
      label: '朱音本人攻略入口',
      yesMeaning: 'User 承认朱音的创作强度、危险性和自毁性，开始与她建立非扁平敌我对话。',
      noMeaning: '朱音仍只作为压力源存在。',
    },
    {
      id: 'akane_repulsed',
      storageKey: 'plotFlag.v07.akane_repulsed',
      earliestDate: '2013-02-25',
      label: '朱音挖角被击退',
      yesMeaning: '已成功阻止朱音带走黑金二人组。',
      noMeaning: '本轮明确表明尚未击退朱音挖角。',
    },
    {
      id: 'second_project_seed_ready',
      storageKey: 'plotFlag.v07.second_project_seed_ready',
      earliestDate: '2013-02-26',
      label: '第二作企划种子可用',
      yesMeaning: '第二作企划初稿足以成为行动基础。',
      noMeaning: '第二作仍只是空口热血。',
    },
    {
      id: 'eriri_high_battlefield_supported',
      storageKey: 'plotFlag.v07.eriri_high_battlefield_supported',
      earliestDate: '2013-02-26',
      label: '英梨梨高强度战场被支持',
      yesMeaning: 'User 给英梨梨提供能燃烧的高强度创作理由，而非单纯保护。',
      noMeaning: 'User 仍只是在保护或挽留英梨梨。',
    },
    {
      id: 'utaha_author_pride_supported',
      storageKey: 'plotFlag.v07.utaha_author_pride_supported',
      earliestDate: '2013-02-26',
      label: '诗羽作者自尊被承认',
      yesMeaning: 'User 承认诗羽作为霞诗子的才能与不死心。',
      noMeaning: '诗羽仍被当作附属或工具。',
    },
    {
      id: 'megumi_coplanner',
      storageKey: 'plotFlag.v07.megumi_coplanner',
      earliestDate: '2013-03-01',
      label: '惠成为共同企划/副代表',
      yesMeaning: '惠已被请回共同企划/副代表位置，拥有纠正、争吵和制衡权。',
      noMeaning: '惠仍只是被动女主角或旁观者。',
    },
    {
      id: 'blackgold_counterwill',
      storageKey: 'plotFlag.v07.blackgold_counterwill',
      earliestDate: '2013-03-04',
      label: '黑金共同击退朱音意志',
      yesMeaning: '黑金共同击退朱音意志成立。',
      noMeaning: '黑金共同反击意志未成立或被破坏。',
    },
    {
      id: 'user_knows_counterwill',
      storageKey: 'plotFlag.v07.user_knows_counterwill',
      earliestDate: '2013-03-04',
      label: 'User 已知道黑金誓约',
      yesMeaning: 'User 已通过转述、画稿或会议得知黑金誓约。',
      noMeaning: 'User 尚不知道黑金誓约。',
    },
    {
      id: 'solo_route_open',
      storageKey: 'plotFlag.v07.solo_route_open',
      earliestDate: '2013-02-25',
      label: '单飞路线入口',
      yesMeaning:
        'User 已在当前现实中明确决定或开始准备脱离 blessing software 与朱音体系，以自己的名义独立推进创作；仅有未来也许会做、愿望、假设或灵感不成立。',
      noMeaning: 'User 本轮明确仍未决定、未准备以自己的名义独立推进创作。',
    },
    {
      id: 'user_stay_commitment_grounded',
      storageKey: 'plotFlag.v07.user_stay_commitment_grounded',
      earliestDate: '2013-03-04',
      label: 'User 留下承诺已落地',
      yesMeaning: 'User 留下的决定已经产生实际后果，而不只是口头意图。',
      noMeaning: 'User 尚未以有后果的行动确认留下。',
    },
    {
      id: 'blackgold_not_staying_confirmed',
      storageKey: 'plotFlag.v07.blackgold_not_staying_confirmed',
      earliestDate: '2013-03-04',
      label: '黑金未固定留下已确认',
      yesMeaning: '英梨梨与诗羽没有作为固定同伴留下的事实已经分别确认。',
      noMeaning: '黑金是否留下仍未获得明确剧情事实。',
    },
    {
      id: 'user_stay_position_available',
      storageKey: 'plotFlag.v07.user_stay_position_available',
      earliestDate: '2013-03-04',
      label: 'User 仍有可留下的位置',
      yesMeaning: '当前组织或项目状态仍允许 User 留下并继续推进。',
      noMeaning: '当前组织或项目状态不支持 User 留下。',
    },
    {
      id: 'user_exit_commitment_grounded',
      storageKey: 'plotFlag.v07.user_exit_commitment_grounded',
      earliestDate: '2013-03-04',
      label: 'User 单飞承诺已落地',
      yesMeaning:
        'User 已采取使其在原组织中的职责、权限或成员身份实际终止的离开行动；仅表达独立意图或讨论将来离开不成立。',
      noMeaning: 'User 只有独立意图，尚未采取有后果的离开行动。',
    },
    {
      id: 'group_exit_without_tomoya_grounded',
      storageKey: 'plotFlag.v07.group_exit_without_tomoya_grounded',
      earliestDate: '2013-03-04',
      label: '除伦也外集体离开已落地',
      yesMeaning:
        '至少一名除 User 与伦也外的具名创作者，已通过有实际后果的行动完成离开原体系并实际加入 User 的同一个独立创作项目；仅邀请、未来承诺、临时合作、各自离开、转投朱音或无人同行均不成立。',
      noMeaning: '无人实际跟随 User 加入独立项目，或集体同行仍只是邀请、未来承诺、假设或旁白概括。',
    },
    {
      id: 'group_exit_participant_snapshot_ready',
      storageKey: 'plotFlag.v07.group_exit_participant_snapshot_ready',
      earliestDate: '2013-03-04',
      label: '集体单飞参与者快照已确认',
      yesMeaning:
        '跟随 User 加入同一独立项目的非空参与者集合已经逐人确认，并与临时合作、未表态或去往其他阵营的人区分。',
      noMeaning: '明确没有人跟随 User，或跟随 User 的参与者范围尚未逐人确认。',
    },
  ],
} as const;
