import type { PlotMachineDefinition } from './types';

export const V07_PLOT_MACHINE: PlotMachineDefinition = {
  id: 'v07',
  targetId: 'route:v07',
  title: '第七卷路线开关',
  proposalWindow: {
    start: '2013-02-25',
    end: '2013-03-31',
  },
  promptWindow: {
    start: '2013-03-04',
    end: '2013-03-31',
  },
  choiceStorageKey: 'plotRoute.v07.choice',
  routes: [
    {
      id: 'stay',
      label: '留下',
      requiredFlagIds: [
        'megumi_coplanner',
        'second_project_seed_ready',
        'blackgold_counterwill',
        'eriri_high_battlefield_supported',
        'utaha_author_pride_supported',
      ],
    },
    {
      id: 'akane',
      label: '红坂朱音',
      requiredFlagIds: ['akane_pressure_seen', 'akane_route_open'],
    },
    {
      id: 'solo',
      label: '单飞',
      requiredFlagIds: ['solo_route_open'],
    },
  ],
  flags: [
    {
      id: 'akane_pressure_seen',
      storageKey: 'plotFlag.v07.akane_pressure_seen',
      earliestDate: '2013-02-25',
      label: '朱音压力已被看见',
      yesMeaning: 'User 已知道红坂朱音压力存在。',
      noMeaning: '本轮明确表明 User 尚未知道红坂朱音压力。',
    },
    {
      id: 'akane_formal_offer_seen',
      storageKey: 'plotFlag.v07.akane_formal_offer_seen',
      earliestDate: '2013-02-25',
      label: '正式挖角已进入视野',
      yesMeaning: '御影亭或《寰域编年纪》的正式挖角压力已被显性得知。',
      noMeaning: '正式挖角尚未进入路线判断。',
    },
    {
      id: 'blackgold_shaken',
      storageKey: 'plotFlag.v07.blackgold_shaken',
      earliestDate: '2013-02-25',
      label: '黑金被朱音战场动摇',
      yesMeaning: '英梨梨、诗羽被红坂朱音提供的高强度战场动摇。',
      noMeaning: '本轮明确表明黑金二人组尚未被朱音战场动摇。',
    },
    {
      id: 'akane_route_open',
      storageKey: 'plotFlag.v07.akane_route_open',
      earliestDate: '2013-02-25',
      label: '朱音本人攻略入口',
      yesMeaning: 'User 承认朱音的创作强度、危险性和自毁性，开始与她建立非扁平敌我对话。',
      noMeaning: '朱音仍只作为压力源存在。',
    },
    {
      id: 'akane_repulsed',
      storageKey: 'plotFlag.v07.akane_repulsed',
      earliestDate: '2013-02-25',
      label: '朱音挖角被击退',
      yesMeaning: '已成功阻止朱音带走黑金二人组。',
      noMeaning: '本轮明确表明尚未击退朱音挖角。',
    },
    {
      id: 'second_project_seed_ready',
      storageKey: 'plotFlag.v07.second_project_seed_ready',
      earliestDate: '2013-02-26',
      label: '第二作企划种子可用',
      yesMeaning: '第二作企划初稿足以成为行动基础。',
      noMeaning: '第二作仍只是空口热血。',
    },
    {
      id: 'eriri_high_battlefield_supported',
      storageKey: 'plotFlag.v07.eriri_high_battlefield_supported',
      earliestDate: '2013-02-26',
      label: '英梨梨高强度战场被支持',
      yesMeaning: 'User 给英梨梨提供能燃烧的高强度创作理由，而非单纯保护。',
      noMeaning: 'User 仍只是在保护或挽留英梨梨。',
    },
    {
      id: 'utaha_author_pride_supported',
      storageKey: 'plotFlag.v07.utaha_author_pride_supported',
      earliestDate: '2013-02-26',
      label: '诗羽作者自尊被承认',
      yesMeaning: 'User 承认诗羽作为霞诗子的才能与不死心。',
      noMeaning: '诗羽仍被当作附属或工具。',
    },
    {
      id: 'megumi_coplanner',
      storageKey: 'plotFlag.v07.megumi_coplanner',
      earliestDate: '2013-03-01',
      label: '惠成为共同企划/副代表',
      yesMeaning: '惠已被请回共同企划/副代表位置，拥有纠正、争吵和制衡权。',
      noMeaning: '惠仍只是被动女主角或旁观者。',
    },
    {
      id: 'blackgold_counterwill',
      storageKey: 'plotFlag.v07.blackgold_counterwill',
      earliestDate: '2013-03-04',
      label: '黑金共同击退朱音意志',
      yesMeaning: '黑金共同击退朱音意志成立。',
      noMeaning: '黑金共同反击意志未成立或被破坏。',
    },
    {
      id: 'user_knows_counterwill',
      storageKey: 'plotFlag.v07.user_knows_counterwill',
      earliestDate: '2013-03-04',
      label: 'User 已知道黑金誓约',
      yesMeaning: 'User 已通过转述、画稿或会议得知黑金誓约。',
      noMeaning: 'User 尚不知道黑金誓约。',
    },
    {
      id: 'solo_route_open',
      storageKey: 'plotFlag.v07.solo_route_open',
      earliestDate: '2013-02-25',
      label: '单飞路线入口',
      yesMeaning: 'User 已明确准备脱离 blessing software 与朱音体系，独立推进自己的创作路线。',
      noMeaning: 'User 本轮明确表示仍未准备独立推进创作路线。',
    },
  ],
} as const;
